Document: ktranslate
Title: Debian ktranslate Manual
Author: <insert document author here>
Abstract: This manual describes what ktranslate is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ktranslate/ktranslate.sgml.gz

Format: postscript
Files: /usr/share/doc/ktranslate/ktranslate.ps.gz

Format: text
Files: /usr/share/doc/ktranslate/ktranslate.text.gz

Format: HTML
Index: /usr/share/doc/ktranslate/html/index.html
Files: /usr/share/doc/ktranslate/html/*.html

  
